mass: 483.35
model: auh
inertial:
  ixx: 301.342
  ixy: 0.936
  ixz: 1.026
  iyy: 286.655
  iyz: -1.637
  izz: 456.989
cog: [0, 0, 0]
# CoB represented wrt ENU convention
cob: [0, 0, 0.0002]
volume: 0.470387
length: 1.97194
height: 1.19385
width: 1.96
base_link: base_link
Ma:
- [700, 0, 0, 0, 0, 0]
- [0, 1200, 0, 0, 0, 0]
- [0, 0, 3500, 0, 0, 0]
- [0, 0, 0, 500, 0, 0]
- [0, 0, 0, 0, 800, 0]
- [0, 0, 0, 0, 0, 200]
# In the model, the damping coefficients are pre-multiplied by -1
linear_damping: [-70, -70, -700, -200, -300, -100]
quad_damping: [-700, -900, -1800, -600, -700, -500]
density: 1028.0