tam:
- [1.0, 1.0, 0.0, 0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
- [0.0, 0.0, 1.0, 1.0, 1.0, 1.0]
- [0.0, 0.0, 0.44900000000000007, 0.449, -0.44905, -0.44905000000000006]
- [0.0, 0.0, -0.5795, 0.5795, -0.5795, 0.5795]
- [-0.8205, 0.82055, 0.0, 0.0, 0.0, 0.0]
