variables:
  - DB_CLIENTS
  - MOOS_MANUAL_OVERIDE
  - MOOS_MANUAL_OVERRIDE
  - RESTART_HELM
  - IVPHELM_REJOURNAL
  - BHV_ABLE_FILTER
  - NAV_X
  - NAV_Y
  - NAV_SPEED
  - NAV_HEADING
  - NAV_DEPTH
  - DEPLOY
  - RETURN
  - MODE
  - STATIONING
  - CONSTHEIGHT
  - DOCKDEPTH_UPDATE
  - DOCKHDG_UPDATES
  - DOCKING_FALLING
  - DOCKINGFAILED
  - HELM_MAP_CLEAR
